### ISSUE TITLE
(Third-party library) Dapper Query Builder - wrapper to build dynamic SQL using string interpolation #1512

### ISSUE THREAD

**Issue by Drizin** [zzzprojects/awesome-dapper#5]
[https://github.com/Drizin/DapperQueryBuilder/](https://github.com/Drizin/DapperQueryBuilder/)

**Dapper Query Builder using String Interpolation and Fluent API**

We all love Dapper and how Dapper is a minimalist library.

This library is a wrapper around Dapper mostly for helping building dynamic SQL queries and commands (as a replacement for [Dapper.SqlBuilder](https://github.com/StackExchange/Dapper/tree/main/Dapper.SqlBuilder)). 

It's based on 2 fundamentals:

1. String Interpolation instead of manually using DynamicParameters
1. Query and Parameters walk side-by-side

Sample usage:

```cs
int maxPrice = 1000;
int maxWeight = 15;
string search = "%Mountain%";

var products = cn.QueryBuilder($@"
    SELECT ProductId, Name, ListPrice, Weight
    FROM [Product]
    WHERE [ListPrice] <= {maxPrice}
    AND [Weight] <= {maxWeight}
    AND [Name] LIKE {search}
    ORDER BY ProductId").Query<Product>();
```

`Query<>` invokes Dapper and automatically passes the underlying SQL statement and Parameters. Additional parameters (transaction, commandTimeout) can still be passed. Underlying SQL will be fully parameterized like:
```sql
SELECT ProductId, Name, ListPrice, Weight
FROM [Product]
WHERE [ListPrice] <= @p0
AND [Weight] <= @p1
AND [Name] LIKE @p2
ORDER BY ProductId
```

You can also start with an initial query and then append dynamic conditions:
```cs
var query = cn.QueryBuilder($"SELECT * FROM [Product] WHERE 1=1");
query.Append($"AND Name LIKE {productName}"); 
query.Append($"AND ProductSubcategoryID = {subCategoryId}"); 
var products = query.Query<Product>(); 
```

Or leaving filters to be described later:
```cs
var cn = new SqlConnection(connectionString);

// You can build the query manually and just use QueryBuilder to replace "where" filters (if any)
var q = cn.QueryBuilder(@"SELECT ProductId, Name, ListPrice, Weight
    FROM [Product]
    /**where**/
    ORDER BY ProductId
    ");
    
// You just pass the parameters as if it was an interpolated string, 
// and QueryBuilder will automatically convert them to Dapper parameters (injection-safe)
q.Where($"[ListPrice] <= {maxPrice}");
q.Where($"[Weight] <= {maxWeight}");
q.Where($"[Name] LIKE {search}");

// Query() will automatically build your query and replace your /**where**/ (if any filter was added)
var products = q.Query<Product>();
```

Mixing and/or filters in structured way:
```cs
q.Where(new Filters(Filters.FiltersType.OR)
{
    new Filters(Filters.FiltersType.AND)
    {
        $"[Weight] <= {maxWeight}",
        $"[Weight] >= {minWeight}",
    }
    new Filter($"[Name] LIKE {search}")
});
```

Chained-methods (Fluent API) if you have something like a QueryBuilder exposed in UI to your end-users:
```cs
var q = cn.QueryBuilder()
    .Select($"ProductId")
    .Select($"Name")
    .Select($"ListPrice")
    .Select($"Weight")
    .From($"[Product]")
    .Where($"[ListPrice] <= {maxPrice}")
    .Where($"[Weight] <= {maxWeight}")
    .Where($"[Name] LIKE {search}")
    .OrderBy($"ProductId"); // there's also GROUP BY, HAVING, ORDERBY, and PAGING (OFFSET/FETCH NEXT)
    
var products = q.Query<Product>();
```

More examples and features [here](https://github.com/Drizin/DapperQueryBuilder/)

**Comment by JonathanMagnan** [comment]
Hello @Drizin ,

Yes, I have seen your post on Reddit last Sunday ;) Surely a good one! We will check how much popular it becomes in a few months!

It has been added in the `Supported Packages` section.

Best Regards,

Jon
